cam:
  H: 680
  W: 1200
  cx: 599.5
  cy: 339.5
  depth_scale: 6553.5
  fx: 600.0
  fy: 600.0
checkpoint_path: null
data:
  frame_limit: 100
  input_path: data/input/Datasets/Replica/office0
  scene_name: office0
dataset_name: replica
debug: true
debug_info: true
device: cuda
mapping:
  downscale_ratio: 2
  k_pooling: 3
  map_every: 5
  max_frame_points: 1e5
project_name: ovo
seed: 0
semantic:
  clip:
    embed_type: fixed_weights
    fusion: l1_medoid
    k_top_views: 10
    mask_res: 384
    model_card: SigLIP-384
    mv_fuser: false
    mv_fuser_ckpt: '20250725_1200'
    use_half: false
    weights_predictor_path: data/input/weights_predictor/base
  depth_filter: true
  kf_queue_delay: 10
  log: true
  match_distance_th: 0.05
  sam:
    masks_base_path: data/working/masks/replica_384_sam2.1_16
    multi_crop: true
    points_per_side: 16
    precomputed: false
    sam_ckpt_path: data/input/sam_ckpts/
    sam_encoder: hiera_l
    sam_version: '2.1'
  segment_every: 10
  track_th: 100
  use_gt_clips: false
  use_gt_masks: false
slam:
  close_loops: true
  config_path: data/working/configs/slam
  save_estimated_cam: true
  slam_module: orbslam3
  use_viewer: false
tracking:
  track_every: 1
use_wandb: false
vis:
  show_stream: false
  stream: false
